spring:
  datasource:
    url: jdbc:h2:file:~/test_db
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
       # default_batch_fetch_size: 1000
  h2:
    console:
      enabled: true
      path: /h2-console
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  webflux:
    hiddenmethod:
      filter:
        enabled: true
logging.level:
  org.hibernate.SQL: debug

